server {
    listen 80;
    server_name yourdomain.com;

    root /var/www/my-frontend/dist;
    index index.html;

    location / {
        try_files $uri /index.html;   # SPA 前端路由
    }

    location /api/ {
        proxy_pass http://114.67.85.146:3000/;  # 反向代理后端
    }
}