server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;   # 修改成容器里的实际路径2
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://114.67.85.146:3000;
    }
}